// <auto-generated />
using System;
using HelpDesk.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelpDesk.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("HelpDesk.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedUser = "admin@system.com",
                            CreatedAt = new DateTime(2025, 12, 27, 8, 52, 1, 878, DateTimeKind.Utc).AddTicks(6935),
                            Description = "Instalar routers y configurar VLANs",
                            Priority = 2,
                            Status = 1,
                            Title = "Configurar entorno de red"
                        },
                        new
                        {
                            Id = 2,
                            AssignedUser = "tech@system.com",
                            CreatedAt = new DateTime(2025, 12, 26, 8, 52, 1, 878, DateTimeKind.Utc).AddTicks(6937),
                            Description = "Actualizar licencias en todas las terminales",
                            Priority = 1,
                            Status = 2,
                            Title = "Actualizar antivirus"
                        },
                        new
                        {
                            Id = 3,
                            AssignedUser = "admin@system.com",
                            CreatedAt = new DateTime(2025, 12, 27, 6, 52, 1, 878, DateTimeKind.Utc).AddTicks(6944),
                            Description = "Atasco de papel recurrente en bandeja 2",
                            Priority = 0,
                            Status = 0,
                            Title = "Error en impresora contabilidad"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
